{{- if .Values.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "baseapp.namespace" . }}
  labels:
    kubernetes.io/metadata.name: {{ include "baseapp.namespace" . }}
{{- end }}
