{{- if .Values.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "baseapp.namespace" . }}
  labels:
    {{- include "baseapp.labels" . | nindent 4 }}
    kubernetes.io/metadata.name: {{ include "baseapp.namespace" . }}
{{- end }}
