apiVersion: v1
kind: Service
metadata:
  name: {{ include "baseapp.servicename" . }}
  namespace: {{ include "baseapp.namespace" . }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "baseapp.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- if .Values.service.httpsPort }}
  - name: https
    port: {{ .Values.service.httpsPort }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort }}
  {{- end }}
  {{- if .Values.service.httpPort }}
  - name: http
    port: {{ .Values.service.httpPort }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort }}
  {{- end }}
  selector:
    {{- include "baseapp.selectorLabels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
